version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.5
    working_directory: /go/nethelp
    steps:
      - checkout
      - run: pwd && ls 
      - run: go install
      - run: nethelp -v
      - run: nethelp --cloud rdc
      - run: nethelp --cloud vdc
      - run: nethelp --dc na
      - run: nethelp --dc eu
      - run: nethelp
